import { FormDataConvertible } from '@inertiajs/core';

export interface FormData {
    code: string;
    name: string;
    slug?: string; // usually auto-generated, can be omitted from form
    category_id: number | null;
    hsn: string | null;
    description: string | null;
    make: string | null;
    model_no: string | null;
    max_capacity: string | null;
    readability: string | null;
    plateform_size: string | null;
    plateform_moc: string | null;
    indicator_moc: string | null;
    load_plate: string | null;
    indicator_mounding: string | null;
    quality: string | null;
    type: 'consumable' | 'spare_part' | 'tool' | 'material' | 'other';
    unit: 'set' | 'nos' | 'rmt' | 'sqm' | 'ltr' | 'kg' | 'ton' | 'box' | 'pack' | 'pcs' | 'na' | null;
    status: 'active' | 'inactive' | 'discontinued' | 'maintenance' | 'retired';
    minimum_stock: number;
    current_stock: number;
    maximum_stock: number | null;
    reorder_point: number | null;
    reorder_quantity: number | null;
    standard_cost: number | null;
    selling_price: number | null;
    rental_rate: number | null;
    specifications: Record<string, any> | null;
    technical_details: Record<string, any> | null;
    safety_data: Record<string, any> | null;
    storage_location: string | null;
    storage_conditions: string | null;
    storage_instructions: string | null;
    manufacturer: string | null;
    supplier: string | null;
    warranty_period: string | null;
    last_purchase_date: string | null;
    last_purchase_price: number | null;
    condition: 'new' | 'good' | 'fair' | 'poor';
    last_maintenance_date: string | null;
    next_maintenance_date: string | null;
    sort_order: number;
    [key: string]: FormDataConvertible;
}

export interface Item {
    id: number;
    code: string;
    name: string;
    slug: string;
    category_id: number | null;
    category?: {
        id: number;
        name: string;
    };
    hsn: string | null;
    description: string | null;
    make: string | null;
    model_no: string | null;
    max_capacity: string | null;
    readability: string | null;
    plateform_size: string | null;
    plateform_moc: string | null;
    indicator_moc: string | null;
    load_plate: string | null;
    indicator_mounding: string | null;
    quality: string | null;
    type: 'consumable' | 'spare_part' | 'tool' | 'material' | 'other';
    unit: 'set' | 'nos' | 'rmt' | 'sqm' | 'ltr' | 'kg' | 'ton' | 'box' | 'pack' | 'pcs' | 'na' | null;
    status: 'active' | 'inactive' | 'discontinued' | 'maintenance' | 'retired';
    minimum_stock: number;
    current_stock: number;
    maximum_stock: number | null;
    reorder_point: number | null;
    reorder_quantity: number | null;
    standard_cost: number | null;
    selling_price: number | null;
    rental_rate: number | null;
    specifications: Record<string, any> | null;
    technical_details: Record<string, any> | null;
    safety_data: Record<string, any> | null;
    storage_location: string | null;
    storage_conditions: string | null;
    storage_instructions: string | null;
    manufacturer: string | null;
    supplier: string | null;
    warranty_period: string | null;
    last_purchase_date: string | null;
    last_purchase_price: number | null;
    condition: 'new' | 'good' | 'fair' | 'poor';
    last_maintenance_date: string | null;
    next_maintenance_date: string | null;
    sort_order: number;
    created_at: string;
    updated_at: string;
    deleted_at: string | null;
    stock_status?: 'low' | 'normal' | 'excess';
}