// Common currency data with symbols
export const CURRENCIES = [
    { value: 'INR', label: 'Indian Rupee (₹)', symbol: '₹' },
    { value: 'USD', label: 'US Dollar ($)', symbol: '$' },
    { value: 'EUR', label: 'Euro (€)', symbol: '€' },
    { value: 'GBP', label: 'British Pound (£)', symbol: '£' },
    { value: 'JPY', label: 'Japanese Yen (¥)', symbol: '¥' },
    { value: 'CAD', label: 'Canadian Dollar (C$)', symbol: 'C$' },
    { value: 'AUD', label: 'Australian Dollar (A$)', symbol: 'A$' },
    { value: 'CHF', label: 'Swiss Franc (CHF)', symbol: 'CHF' },
    { value: 'CNY', label: 'Chinese Yuan (¥)', symbol: '¥' },
    { value: 'SGD', label: 'Singapore Dollar (S$)', symbol: 'S$' },
    { value: 'AED', label: 'UAE Dirham (د.إ)', symbol: 'د.إ' },
    { value: 'SAR', label: 'Saudi Riyal (ر.س)', symbol: 'ر.س' },
    { value: 'QAR', label: 'Qatari Riyal (ر.ق)', symbol: 'ر.ق' },
    { value: 'KWD', label: 'Kuwaiti Dinar (د.ك)', symbol: 'د.ك' },
    { value: 'BHD', label: 'Bahraini Dinar (د.ب)', symbol: 'د.ب' },
    { value: 'OMR', label: 'Omani Rial (ر.ع)', symbol: 'ر.ع' },
    { value: 'JOD', label: 'Jordanian Dinar (د.ا)', symbol: 'د.ا' },
    { value: 'LBP', label: 'Lebanese Pound (ل.ل)', symbol: 'ل.ل' },
    { value: 'EGP', label: 'Egyptian Pound (ج.م)', symbol: 'ج.م' },
    { value: 'TRY', label: 'Turkish Lira (₺)', symbol: '₺' },
    { value: 'RUB', label: 'Russian Ruble (₽)', symbol: '₽' },
    { value: 'KRW', label: 'South Korean Won (₩)', symbol: '₩' },
    { value: 'THB', label: 'Thai Baht (฿)', symbol: '฿' },
    { value: 'MYR', label: 'Malaysian Ringgit (RM)', symbol: 'RM' },
    { value: 'IDR', label: 'Indonesian Rupiah (Rp)', symbol: 'Rp' },
    { value: 'PHP', label: 'Philippine Peso (₱)', symbol: '₱' },
    { value: 'VND', label: 'Vietnamese Dong (₫)', symbol: '₫' },
    { value: 'BRL', label: 'Brazilian Real (R$)', symbol: 'R$' },
    { value: 'MXN', label: 'Mexican Peso ($)', symbol: '$' },
    { value: 'ARS', label: 'Argentine Peso ($)', symbol: '$' },
    { value: 'CLP', label: 'Chilean Peso ($)', symbol: '$' },
    { value: 'COP', label: 'Colombian Peso ($)', symbol: '$' },
    { value: 'PEN', label: 'Peruvian Sol (S/)', symbol: 'S/' },
    { value: 'ZAR', label: 'South African Rand (R)', symbol: 'R' },
    { value: 'NGN', label: 'Nigerian Naira (₦)', symbol: '₦' },
    { value: 'KES', label: 'Kenyan Shilling (KSh)', symbol: 'KSh' },
    { value: 'GHS', label: 'Ghanaian Cedi (₵)', symbol: '₵' },
    { value: 'UGX', label: 'Ugandan Shilling (USh)', symbol: 'USh' },
    { value: 'TZS', label: 'Tanzanian Shilling (TSh)', symbol: 'TSh' },
    { value: 'ETB', label: 'Ethiopian Birr (Br)', symbol: 'Br' },
    { value: 'MAD', label: 'Moroccan Dirham (د.م)', symbol: 'د.م' },
    { value: 'TND', label: 'Tunisian Dinar (د.ت)', symbol: 'د.ت' },
    { value: 'DZD', label: 'Algerian Dinar (د.ج)', symbol: 'د.ج' },
    { value: 'LYD', label: 'Libyan Dinar (ل.د)', symbol: 'ل.د' },
    { value: 'SDG', label: 'Sudanese Pound (ج.س)', symbol: 'ج.س' },
    { value: 'PKR', label: 'Pakistani Rupee (₨)', symbol: '₨' },
    { value: 'BDT', label: 'Bangladeshi Taka (৳)', symbol: '৳' },
    { value: 'LKR', label: 'Sri Lankan Rupee (Rs)', symbol: 'Rs' },
    { value: 'NPR', label: 'Nepalese Rupee (₨)', symbol: '₨' },
    { value: 'MMK', label: 'Myanmar Kyat (K)', symbol: 'K' },
    { value: 'KHR', label: 'Cambodian Riel (៛)', symbol: '៛' },
    { value: 'LAK', label: 'Lao Kip (₭)', symbol: '₭' },
    { value: 'MNT', label: 'Mongolian Tugrik (₮)', symbol: '₮' },
    { value: 'KZT', label: 'Kazakhstani Tenge (₸)', symbol: '₸' },
    { value: 'UZS', label: 'Uzbekistani Som (UZS)', symbol: 'UZS' },
    { value: 'TJS', label: 'Tajikistani Somoni (ЅМ)', symbol: 'ЅМ' },
    { value: 'KGS', label: 'Kyrgyzstani Som (с)', symbol: 'с' },
    { value: 'GEL', label: 'Georgian Lari (₾)', symbol: '₾' },
    { value: 'AMD', label: 'Armenian Dram (֏)', symbol: '֏' },
    { value: 'AZN', label: 'Azerbaijani Manat (₼)', symbol: '₼' },
    { value: 'BYN', label: 'Belarusian Ruble (Br)', symbol: 'Br' },
    { value: 'MDL', label: 'Moldovan Leu (L)', symbol: 'L' },
    { value: 'UAH', label: 'Ukrainian Hryvnia (₴)', symbol: '₴' },
    { value: 'PLN', label: 'Polish Złoty (zł)', symbol: 'zł' },
    { value: 'CZK', label: 'Czech Koruna (Kč)', symbol: 'Kč' },
    { value: 'HUF', label: 'Hungarian Forint (Ft)', symbol: 'Ft' },
    { value: 'RON', label: 'Romanian Leu (lei)', symbol: 'lei' },
    { value: 'BGN', label: 'Bulgarian Lev (лв)', symbol: 'лв' },
    { value: 'HRK', label: 'Croatian Kuna (kn)', symbol: 'kn' },
    { value: 'RSD', label: 'Serbian Dinar (дин)', symbol: 'дин' },
    { value: 'ALL', label: 'Albanian Lek (L)', symbol: 'L' },
    { value: 'MKD', label: 'Macedonian Denar (ден)', symbol: 'ден' },
    { value: 'BAM', label: 'Bosnia-Herzegovina Convertible Mark (KM)', symbol: 'KM' },
    { value: 'ISK', label: 'Icelandic Króna (kr)', symbol: 'kr' },
    { value: 'NOK', label: 'Norwegian Krone (kr)', symbol: 'kr' },
    { value: 'SEK', label: 'Swedish Krona (kr)', symbol: 'kr' },
    { value: 'DKK', label: 'Danish Krone (kr)', symbol: 'kr' },
    { value: 'FIM', label: 'Finnish Markka (mk)', symbol: 'mk' },
    { value: 'NLG', label: 'Dutch Guilder (ƒ)', symbol: 'ƒ' },
    { value: 'BEF', label: 'Belgian Franc (fr)', symbol: 'fr' },
    { value: 'ITL', label: 'Italian Lira (₤)', symbol: '₤' },
    { value: 'ESP', label: 'Spanish Peseta (₧)', symbol: '₧' },
    { value: 'PTE', label: 'Portuguese Escudo ($)', symbol: '$' },
    { value: 'GRD', label: 'Greek Drachma (₯)', symbol: '₯' },
    { value: 'IEP', label: 'Irish Pound (£)', symbol: '£' },
    { value: 'ATS', label: 'Austrian Schilling (S)', symbol: 'S' },
    { value: 'DEM', label: 'German Mark (DM)', symbol: 'DM' },
    { value: 'FRF', label: 'French Franc (₣)', symbol: '₣' },
    { value: 'LUF', label: 'Luxembourg Franc (fr)', symbol: 'fr' },
    { value: 'MTL', label: 'Maltese Lira (₤)', symbol: '₤' },
    { value: 'CYP', label: 'Cypriot Pound (£)', symbol: '£' },
    { value: 'SIT', label: 'Slovenian Tolar (SIT)', symbol: 'SIT' },
    { value: 'SKK', label: 'Slovak Koruna (Sk)', symbol: 'Sk' },
    { value: 'EEK', label: 'Estonian Kroon (kr)', symbol: 'kr' },
    { value: 'LVL', label: 'Latvian Lats (Ls)', symbol: 'Ls' },
    { value: 'LTL', label: 'Lithuanian Litas (Lt)', symbol: 'Lt' },
];

// Helper function to get currency symbol
export const getCurrencySymbol = (currencyCode: string): string => {
    const currency = CURRENCIES.find(c => c.value === currencyCode);
    return currency ? currency.symbol : currencyCode;
};

// Helper function to get currency data for Select components
export const getCurrencyOptions = () => {
    return CURRENCIES.map(currency => ({
        value: currency.value,
        label: currency.label
    }));
};

// Default currency
export const DEFAULT_CURRENCY = 'INR'; 